apiVersion:   v1
kind: Service
metadata:
  name: result-service
  namespace: vote
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 31001
  selector:
    app: result
  type: NodePort
