apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: vote
  labels: 
    app: result
spec:
  replicas: 2
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      name: result
      labels:
        app: result
    spec:
      containers:
      - name: result 
        image: docker/example-voting-app-result
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: 0.1
          limits:
            memory: "128Mi"
            cpu: 0.3

